### ISSUE TITLE
Difference between Minerva and MShadow

### ISSUE THREAD

**Issue by jrabary** [dmlc/minerva#20]
Dear all,

I was surprised too see that Minerva is now part of the umbrella project DMLC. So I'm a little bit lost in the middle of these awesome tools. What is the difference between them ? Especially between minerva, mshadow and Cxxnet. I'm interested in implementing a distributed version of a triplet convolutional network that I have in Caffe.

**Comment by tqchen** [comment]
To be short, minerva is dynamic while mshadow is static.

Minerva is a project that is more numpy(torch) style that offers nice dynamic compilation properties. 
While  mshadow is a static template compilation library that allows you to write expressions, and compile to code as if you handcraft the kernels in caffe. So mshadow and cxxnet goes for conciseness for maximum performance and memory control. 

In your case, I guess it would be easier to start from cxxnet, since it is closer to caffe, and you can even use mshadow to write caffe kernels.

Eventually, minerva and cxxnet will merge into one project to offer the nice properties of both nature, to allow quick customization with dynamic scripting, while being able to plugin static component that is heavily optimized.

Hope this answers your question
Tianqi

**Comment by jrabary** [comment]
Thank you Tianqi. It is more clear now. So, if I get it right, mshadow is an optimized tensor library and it doesn't use things such as data flow paradigm ?

**Comment by tqchen** [comment]
mshadow is a statically optimized tensor library. Which means operations such as W = W+ eta * dW will be compiled into single cuda kernel, which offers you the same performance as handcrafted one. But there is no dataflow engine behind the scene. 

Minerva's dataflow engine offers global level of scheduling that could eventually benefit mshadow's optimized local operations

**Comment by jermainewang** [comment]
Thanks for Tianqi's comments.
Another difference between Minerva and cxxnet is the distributed version. CXXnet uses parameter server for data parallelism, while for Minerva, since it has its own dataflow engine, it could do data parallelism itself. We now only support multiple GPUs on single machine, so if you are targeting this scenario, you could use Minerva's interface to have a try. But if you are implementing a distributed version cross machines, i think it's better to directly utilize cxxnet's operation as the basic computing unit (in fact, Minerva will try to use them as well in our future plan).
