### ISSUE TITLE
script to convert the pre-trained model to caffe format

### ISSUE THREAD

**Issue by metalbubble** [dmlc/minerva#24]
I am very interested in the minerva project and glad to deploy minerva on our lab servers. But currently we have a lot of existing codes that are largely only compatible with caffe. I am wondering if you could provide a script that could convert the networks trained by minerva back to caffe format. I think it will help grab the attention of caffe users and gradually turn them to minerva :)

**Comment by sneakerkg** [comment]
Thanks very much for your interests in Minerva.
Your suggestion is valuable, we'll try to add one asap, hope it won't keep you waiting for long.

Since we're trying to build Minerva more user-friendly and capable of adapting works on other platforms more easily, may I ask what have you implemented in Caffe? New layers, new processing pipeline? It will help us with new designs.

**Comment by sneakerkg** [comment]
Hi all, we've added the python script to convert model between Caffe and Minerva, both way. Please check: https://github.com/dmlc/minerva/tree/master/scripts/modelconvertor

Thanks.
