### ISSUE TITLE
Failed to run MNIST example due to CudaPerformNormAddOnRow CUDA: invalid device function

### ISSUE THREAD

**Issue by zer0n** [dmlc/minerva#32]
```
(Owl Ready) ➜  mnist: python mnist_mlp.py
[18:48:23] /home/zer0n/minerva/minerva/system/minerva_system.cpp:86: dag engine enabled
Training data: 235 mini-batches
Test data: 10000 samples
(256, 10)
---Start epoch #0
[18:48:28] /home/zer0n/minerva/minerva/op/impl/cuda/cuda_perform.cu:136: Check failed: (e) == (cudaSuccess) CudaPerformNormAddOnRow CUDA: invalid device function
[1]    72399 abort (core dumped)  python mnist_mlp.py
```

My environment:
- Minerva built with `cmake 3.2.3` and `g++ 4.9` on Ubuntu 12.04
- CUDA 7
- CuDNN 2  

FYI, I ran Caffe's MNIST example using GPU just fine.

**Comment by hjk41** [comment]
"invalid device function" is usually caused by old GPU:
https://github.com/dmlc/minerva/wiki/FAQ
For maximum performance, we compile GPU code for compute capability 35,
while you might have an older GPU. Please follow the following two steps:

   1. Lookup the "compute capability" of your GPU in this page
   <http://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units>.
   2. Modify {minerva_root_dir}\CMakeLists.txt, in line 104, replace
set(CUDA_NVCC_FLAGS
   "-arch sm_35") with set(CUDA_NVCC_FLAGS "-arch
   sm_{your_compute_capability}")


On Sun, Jun 14, 2015 at 2:52 AM, zer0n <notifications@github.com> wrote:

> (Owl Ready) ➜  mnist: python mnist_mlp.py
> [18:48:23] /home/zer0n/minerva/minerva/system/minerva_system.cpp:86: dag engine enabled
> Training data: 235 mini-batches
> Test data: 10000 samples
> (256, 10)
> ---Start epoch #0
> [18:48:28] /home/zer0n/minerva/minerva/op/impl/cuda/cuda_perform.cu:136: Check failed: (e) == (cudaSuccess) CudaPerformNormAddOnRow CUDA: invalid device function
> [1]    72399 abort (core dumped)  python mnist_mlp.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/minerva/issues/32>.
>



-- 
HONG Chuntao
System Research Group
Microsoft Research Asia
